/**
 * Locality Filter
 *
 * Ensures that candidates are local to the user's selection.
 * Filters out candidates that don't match the selected region.
 */

import { injectable } from "tsyringe";

/**
 * Candidate interface (minimal definition for filtering)
 */
export interface Candidate {
  id: string;
  targetPath: string;
  [key: string]: any;
}

/**
 * LocalityFilter - Filters candidates based on locality to selection
 */
@injectable()
export class LocalityFilter {
  /**
   * Apply locality filtering to candidates
   *
   * @param candidates - Array of candidates to filter
   * @param selectionPath - The path selected by the user
   * @param resolvedSelectionPath - The resolved AST path from MapMaster
   * @returns Filtered array of candidates
   */
  apply<T extends Candidate>(
    candidates: T[],
    selectionPath: string | null | undefined,
    resolvedSelectionPath: string | null | undefined
  ): T[] {
    return candidates.filter((candidate) =>
      this.isLocalToSelection(selectionPath, resolvedSelectionPath, candidate)
    ) as T[];
  }

  /**
   * Checks if a candidate is local to the user's selection.
   * For Stage-1, we enforce strict equality between the candidate's target path
   * and the selection path.
   *
   * @param selectionPath - The path selected by the user (e.g., "term[0].op")
   * @param selectionAstPath - The resolved AST path from MapMaster
   * @param candidate - The candidate step generated by MapMaster
   * @returns true if the candidate is local to the selection, false otherwise
   */
  private isLocalToSelection(
    selectionPath: string | null | undefined,
    selectionAstPath: string | null | undefined,
    candidate: Candidate
  ): boolean {
    // 1) If we have an AST selection anchor, use it
    if (selectionAstPath && selectionAstPath.trim() !== "") {
      const anchor = selectionAstPath.trim();
      const target = candidate.targetPath;

      if (target === anchor) return true;
      if (target === "root") return true; // Root contains everything
      if (anchor.startsWith(target + ".")) return true;
      if (target.startsWith(anchor + ".")) return true;
      return false;
    }

    // 2) Fallback: no AST anchor → do NOT enforce locality for now
    return true;
  }
}
